ALTER TABLE "Account"
ADD COLUMN "icon" TEXT NOT NULL DEFAULT 'wallet',
ADD COLUMN "color" TEXT NOT NULL DEFAULT '#EF4444';

ALTER TABLE "Category"
ADD COLUMN "icon" TEXT NOT NULL DEFAULT 'tag',
ADD COLUMN "color" TEXT NOT NULL DEFAULT '#6366F1';
